.create-merge table Run(JobId:string, State:string, Timestamp:datetime)

.alter table Run policy streamingingestion enable

.create-merge table RunStep(
    JobId:string,
    Breadcrumb:dynamic,
    State:string,
    Script:string,
    CaptureName:string,
    IsResultScalar:bool,
    ResultColumnNames:dynamic,
    ResultColumnTypes:dynamic,
    ResultData:dynamic,
    Timestamp:datetime)

.alter table RunStep policy streamingingestion enable
