parameters:
  appVersionTxtPath:  ''
  appVersionCsPath:  ''
  imageName:  ''
jobs:
  - deployment:  build_container
    displayName: Build Container
    environment:  build
    pool:
      vmImage: 'ubuntu-latest'
    variables: []
    strategy:
      runOnce:
        deploy:
          steps:
          # Checkout:  https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git#checkout
          - checkout: self
          # Bash script:  https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/bash?view=azure-devops
          - task: Bash@3
            inputs:
              targetType: inline
              script: mkdir package
          # Python script:  https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/python-script
          - task: PythonScript@0
            displayName: 'Manage Version'
            inputs:
              scriptPath: 'common/deployment/manage-version.py'
              arguments: '${{ parameters.appVersionTxtPath }} ${{ parameters.appVersionCsPath }} $(Build.BuildId) package/full-version.txt'
          # .NET Core tests:  https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core#run-your-tests
          - task: DotNetCoreCLI@2
            displayName: 'Run Unit Tests'
            inputs:
              command: test
              projects: 'components/api-front-end/**/*UnitTest*/*.csproj'
              arguments: --configuration release
          # .NET Core publish:  https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli#publish
          - task: DotNetCoreCLI@2
            displayName: 'Build / Publish'
            inputs:
              command: publish
              projects: 'components/api-front-end/api-front-end-solution/ApiFrontEnd/*.csproj'
              publishWebProjects: True
              arguments: --configuration release --output build-output
              zipAfterPublish: False
          - script:  pwd
          - script:  ls -l build-output
          # Build Docker:  https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker#build-and-push
          - task: Docker@2
            displayName: Build and push Docker Image
            inputs:
              containerRegistry:  docker-hub
              repository: ${{ parameters.imageName }}
              command:  buildAndPush
              Dockerfile: 'components/api-front-end/**/Dockerfile'
              tags: '$(full-version)'
          # Publish artefacts:  https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact'
            inputs:
              targetPath: package
              artifactName: package
          # # Copy files:  https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/copy-files
          # - task: CopyFiles@2
          #   displayName:  Copy deployment directory
          #   inputs:
          #     sourceFolder: package
          #     targetFolder: $(Build.ArtifactStagingDirectory)/package/
          # # Publish artefacts:  https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts
          # - task: PublishBuildArtifacts@1
          #   displayName: 'Publish Artifact'
          #   inputs:
          #     targetPath: $(Build.ArtifactStagingDirectory)/deployment
          #     artifactName: package
