# Help:  https://aka.ms/yaml

resources:
- repo: self

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - components/api-status/*

stages:
  - stage: build
    displayName: build
    dependsOn:  []
    jobs:
      # Docker Hub Repo:  https://hub.docker.com/repository/docker/vplauzon/status-api-kusto-x
      - template: ../../../common/deployment/container-build.yaml
        parameters:
          appVersionTxtPath:  components/api-status/deployment/api-version-prefix.txt
          appVersionCsPath:  components/api-status/api-status-solution/ApiStatus/ApiVersion.cs
          componentName:  api-status
          projectName:  ApiStatus
          imageName: vplauzon/status-api-kusto-x
  - stage: dev
    displayName: dev
    dependsOn:  build
    jobs:
      - template: ../../../common/deployment/container-tag.yaml
        parameters:
          environment:  dev
          tag:  experimental
          imageName: vplauzon/status-api-kusto-x
