# Help:  https://aka.ms/yaml

resources:
- repo: self

trigger:
- master

stages:
  - stage: build
    displayName: build
    dependsOn:  []
    jobs:
      # Docker Hub Repo:  https://hub.docker.com/repository/docker/vplauzon/pas-api
      - template: helm-build.yaml
        parameters:
          appVersionTxtPath:  code/api-front-end/deployment/api-version-prefix.txt
          appVersionCsPath:  code/api-front-end/api-front-end-solution/ApiFrontEnd/ApiVersion.cs
          imageName: vplauzon/front-end-api-kusto-x

  - stage: dev
    displayName: dev
    dependsOn:  build
    jobs:
      - template: helm-deploy.yaml
        parameters:
          environment:  dev
          chartName: pas-api
