# Help:  https://aka.ms/yaml

resources:
- repo: self

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - components/web-portal/*

stages:
  - stage: build
    displayName: build
    dependsOn:  []
    jobs:
      # Docker Hub Repo:  https://hub.docker.com/repository/docker/vplauzon/web-portal-kusto-x
      - template: ../../../common/deployment/container-build.yaml
        parameters:
          appVersionTxtPath:  components/web-portal/deployment/app-version-prefix.txt
          appVersionCsPath:  components/web-portal/web-portal-solution/WebPortal/AppVersion.cs
          componentName:  web-portal
          projectName:  WebPortal
          imageName: vplauzon/web-portal-kusto-x
  - stage: dev
    displayName: dev
    dependsOn:  build
    jobs:
      - template: ../../../common/deployment/container-tag.yaml
        parameters:
          environment:  dev
          tag:  experimental
          imageName: vplauzon/web-portal-kusto-x
