name:  Infrastructure Deployment

on:
  workflow_dispatch

jobs:
  registry:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Determine current environment
      run: |
        echo "Branch name:  ${{ github.ref_name }}"
        environment=$(bash deployment/retrieve-environment.sh ${{ github.ref_name }})
        echo "Environment:  $environment"
        echo "environment=$environment" >> $GITHUB_ENV

    - name: Azure Login
      run: az login --service-principal -u ${{ secrets.DEPLOY_CLIENT_ID }} -p ${{ secrets.DEPLOY_SECRET }} --tenant ${{ secrets.TENANT_ID }}
    - name: Azure Subscription Set
      run: az account set --name ${{ secrets.SUBSCRIPTION }}

    - name: Deploy container registry
      run: |
        cd deployment/registry
        bash deploy-registry.sh ${{ secrets.RESOURCE_GROUP }} $environment

  workbench:
    needs:
    - registry
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.x
    - name: Determine current environment
      run: |
        echo "Branch name:  ${{ github.ref_name }}"
        environment=$(bash deployment/retrieve-environment.sh ${{ github.ref_name }})
        echo "Environment:  $environment"
        echo "environment=$environment" >> $GITHUB_ENV
    - name: Patch version
      id:  patch-version
      run: python3 deployment/manage-version.py code/Kustox.WebPortal/Kustox.WebPortal.csproj ${{ github.run_number }}
    - name: Install dependencies
      run: dotnet restore code
    - name: .NET Build
      run: dotnet build code/Kustox.WebPortal --configuration Release --no-restore
    - name: .NET Publish Web App
      run: dotnet publish code/Kustox.WebPortal --configuration Release --no-restore --output bin

    - name: Azure Login
      run: az login --service-principal -u ${{ secrets.DEPLOY_CLIENT_ID }} -p ${{ secrets.DEPLOY_SECRET }} --tenant ${{ secrets.TENANT_ID }}
    - name: Azure Subscription Set
      run: az account set --name ${{ secrets.SUBSCRIPTION }}
    - name: Retrieve docker registry
      run: |
        echo "Environment:  $environment"
        registry=$(az acr list -g ${{ secrets.RESOURCE_GROUP }} --query "[?starts_with(@.name, '$environment')].name" -o tsv)
        echo 'Registry:  $registry'
        az acr login --name $registry

  infra:
    needs:
    - workbench
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Determine current environment
      run: |
        echo "Branch name:  ${{ github.ref_name }}"
        environment=$(bash deployment/retrieve-environment.sh ${{ github.ref_name }})
        echo "Environment:  $environment"
        echo "environment=$environment" >> $GITHUB_ENV
    - name: Azure Login
      run: az login --service-principal -u ${{ secrets.DEPLOY_CLIENT_ID }} -p ${{ secrets.DEPLOY_SECRET }} --tenant ${{ secrets.TENANT_ID }}
    - name: Azure Subscription Set
      run: az account set --name ${{ secrets.SUBSCRIPTION }}

    - name: Deploy infra
      run: |
        cd deployment/infra
        bash deploy-infra.sh ${{ secrets.RESOURCE_GROUP }} $environment
