name:  Shell Dev Deploy

on:
  workflow_dispatch

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Azure Login
      run: az login --service-principal -u ${{ secrets.sp_id }} -p ${{ secrets.sp_secret }} --tenant ${{ secrets.tenant_id }}
    - name: Testing one-two
      run: az group list -o table
      
