name:  Continuous Build / Test

on:
  push:
    branches:
      - master
    #paths:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - run: pwd
    - name: Change Directory
      run: cd components/web-portal/web-portal-solution
    - run: pwd
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test **/*UnitTest --no-restore --verbosity normal
    
